### ISSUE TITLE
Experimental Details

### ISSUE THREAD

**Issue by zhangyahu1** [zju3dv/SMAP#1]
Thanks for sharing your great work!
I have a question about your experimental details on CMU Panoptic dataset: which sequences do you train and test on?

**Comment by miaowu99** [comment]
train:
160224_haggling1
160226_mafia2
160224_mafia1
160224_mafia2
160224_ultimatum1
160224_ultimatum2

valid:
160422_mafia2

test sampled from：
160226_haggling1
160422_haggling1
160226_mafia1
160226_ultimatum1
160422_ultimatum1
160906_pizza1

**Comment by zhangyahu1** [comment]
Thanks for quick your response!
I download the dataset. However, some 3D annotations from activities are not provided, such as the activity of mafia, 160224_ultimatum1 and 160224_ultimatum2. How do you solve this problem?

**Comment by miaowu99** [comment]
This is because some annotations of Panoptic only support coco15, you can try to remove the suffix "coco19" of the download path.

**Comment by zhangyahu1** [comment]
Thanks!

**Comment by xiaochehe** [comment]
> train: 160224_haggling1 160226_mafia2 160224_mafia1 160224_mafia2 160224_ultimatum1 160224_ultimatum2
> 
> valid: 160422_mafia2
> 
> test sampled from： 160226_haggling1 160422_haggling1 160226_mafia1 160226_ultimatum1 160422_ultimatum1 160906_pizza1

Dear authors, do the training samples also come from the cameras 16 and 30?
