### ISSUE TITLE
error in testing

### ISSUE THREAD

**Issue by lan786** [zju3dv/SMAP#10]
Thanks for this great repo. I'm trying to run the code from pretrained SMAP and RefineNet. I followed the instructions same as [Run inference on custom images](https://github.com/zju3dv/SMAP#run-inference-on-custom-images) but I'm getting following error (attached error screenshot) in stage3_root2 test.sh

![error](https://user-images.githubusercontent.com/40846865/93729955-1b335980-fbf9-11ea-97ca-5c3181fcc53f.png)

My system environment is Ubuntu 18.04,Python 3.7 and torch 1.4

Is there any need to provide MuCo datasets for inference from pretrained models?

**Comment by raypine** [comment]
Is dapalib installed correctly ? There is no need to provide MuCo datasets for inference on custom images.

**Comment by lan786** [comment]
Yes dapalib is installed. 
My CUDA version is 9.0 and GCC 6.5
Before it GCC version was 7.5 and complication was unsuccessful. I downgraded GCC and then complication was successful.

**Comment by raypine** [comment]
We have not faced this problem yet. You can debug extensions/association.cpp/findConnectedJoints function if possible (by cout sth ... ).
