### ISSUE TITLE
how to convert coco json

### ISSUE THREAD

**Issue by leonzgtee** [zju3dv/SMAP#11]
could you tell me how to convert coco to the format you mentioned in lib/preprocess/data_format.md. no 3d keypoints is available.

**Comment by raypine** [comment]
Just set zeros if no 3d supervision is available.  For coco, [x, y, Z, v, X, Y, Z, fx, fy, cx, cy] --> [x, y, 0, v, 0, 0, 0, fx, fy, cx, cy].

**Comment by leonzgtee** [comment]
thanks,  but some keypoints cannot find in coco annotation,for example, neck/head/pelvis in MPII  cannot find in coco. can you share your convert script.

**Comment by raypine** [comment]
refer to lib/preprocess/create_annot.py

**Comment by leonzgtee** [comment]
@raypine thank you for providing the create_annot.py, but i find that code about neck is annotated ,      """
            body_new[1][0] = (body[0][0] - body_new[0][0]) + body[0][0]
            body_new[1][1] = (body[0][1] - body_new[0][1]) + body[0][1]
            body_new[1][3] = min(body[0][2], body_new[0][3])
            """
is this keypints set to zeros when converted to MPI 15 format,

**Comment by raypine** [comment]
In dataset/base_dataset.py, you will find that head in coco dataset is not supervised ([here](https://github.com/zju3dv/SMAP/blob/master/dataset/base_dataset.py#L170)), which means whether setting zeros or not will not matter in data conversion.

**Comment by leonzgtee** [comment]
thanks you!

**Comment by leonzgtee** [comment]
@raypine sorry to interrupt you again. i have converted coco and MuCo data to the required format. when start training , i find that the loss of loss_bone is too large(about 40000). there maybe someting wrong with my MuCo data. is there anything i should pay more attention to. thanks
