### ISSUE TITLE
Error with tesh.sh (dapalib fails)

### ISSUE THREAD

**Issue by minhpvo** [zju3dv/SMAP#12]
Thanks for this great repo. I'm trying to run the code from pretrained SMAP. I followed the instructions same as Run inference on custom images but I'm getting following error (attached error screenshot) in stage3_root2 test.sh

![Capture](https://user-images.githubusercontent.com/8794025/94335745-7f0ba880-ff92-11ea-80bb-f9931562c5bd.PNG)

My environment is torch1.5.0,  torchvision0.6, and gcc 7.5c.

I am looking forward to hear from you!

**Comment by raypine** [comment]
What's your CUDA version ? CUDA 10.1 seems compatible.

**Comment by minhpvo** [comment]
I have cuda 10.2. It appears to be a confusion between python and python3.
