### ISSUE TITLE
MuPoTS dataset eval issue

### ISSUE THREAD

**Issue by YangJae96** [zju3dv/SMAP#14]
The pred_2d and pred_3d has 15 joints which has no head and spine joints.

1. Did you change the  (pred_2d and pred_3d) 15 joints to MuPoTs 17 joints (adding head and spine manually) 
before putting results  "pred_2d" and "pred_3d" 
into the Moon's  mpii_mupots_multiperson_eval.m code??
Do I need to add head and spine in array 15,16?

2. In matlab code, 
should I set the safe_traversal_order = [2,1,10,11,12,4,5,6,13,14,15,7,8,9,3] 
and num_joints = 15?

**Comment by raypine** [comment]
We convert our format to that of Moon and only evaluate the first fifteen keypoints.

**Comment by raypine** [comment]
The specific process is as follows:
```
load our data
pred_3d_kpt = pred_3d_kpt(:, [2,1,10,11,12,4,5,6,13,14,15,7,8,9,3], :);
set safe_traversal_order = [15, 2, 1, 3, 4, 5, 6, 7, 8, 9:14]
```
