### ISSUE TITLE
Root depth map

### ISSUE THREAD

**Issue by zhangyahu1** [zju3dv/SMAP#16]
Thanks for sharing your nice work!

As mentioned in your paper, the size of root depth map is the same as the input image image. However, I find it seems that 
(1)the root joint locations are also reduced by a quarter as 2d heatmap in base_dataset.py; 
(2) root joint locations are used to regress 3D pose instead of using root depth map.

Maybe I miss some points.

**Comment by raypine** [comment]
1) Actually, the root depth map has the same size as other heatmap representations (scaled, not the original size of the image). 
2) What do you mean by using root depth map to regress 3D pose ?

**Comment by zhangyahu1** [comment]
I am sorry that I did not express the second question clear.
In base_dataset.py, I notice that only root joint locations are generated using the function of generate_rdepth, i.e, a matrix of NX3, but not root depth map.

**Comment by raypine** [comment]
Yes. Root depth map from our smap network is in the form of a map representation, while the supervision is in the form of N x 3. Since we only supervise the place of the root joint, therefore there is no need to represent the supervision in base_dataset.py as a map representation.

**Comment by zhangyahu1** [comment]
I see. So the root depth map is only the intermediate output in your network, and then it is supervised by the matrix of root locations (in the form of N x 3)?

**Comment by raypine** [comment]
Yes. For more details, please refer to [here](https://github.com/zju3dv/SMAP/blob/master/lib/utils/loss_h.py#L10).

**Comment by zhangyahu1** [comment]
Thanks!

**Comment by zhangyahu1** [comment]
Hi,
I notice the loss of root depth map is based on the real root joint positions in image space, i.e. x and y are from GT, and then the value Z in real space is obtained. Do you also use it to obtain the depth value in testing stage?

**Comment by raypine** [comment]
No. We use estimated 2d root positions from heatmaps. Please refer to [here](https://github.com/zju3dv/SMAP/blob/master/extensions/association.cpp#L140).

**Comment by zhangyahu1** [comment]
Thanks!
