### ISSUE TITLE
Error in testing

### ISSUE THREAD

**Issue by 4AMZGGO1** [zju3dv/SMAP#18]
when running inferece on custom images, the error are as follows:
`Traceback (most recent call last):
  File "test.py", line 22, in <module>
    import dapalib
ImportError: /home/dell/anaconda3/envs/SMAP/lib/python3.7/site-packages/dapalib-0.0.0-py3.7-linux-x86_64.egg/dapalib.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E`

Have you encountered this question before and could you give me any solution?

**Comment by RanFeng** [comment]
hello, i have same question, could you give me your solution? thanks for your reply!

**Comment by 4AMZGGO1** [comment]
emmm，I solved the problem by changing a machine. And my environment is gcc7.5+ cuda10.1 + pytorch1.4.

**Comment by 4AMZGGO1** [comment]
> hello, i have same question, could you give me your solution? thanks for your reply!

emmm，I solved the problem by changing a machine. And my environment is gcc7.5+ cuda10.1 + pytorch1.4.

**Comment by RanFeng** [comment]
thank you!

**Comment by visonpon** [comment]
Hi,  @4AMZGGO1, I modified my environment as you did, but when test, I got another error: `RunTimeError:  scan failed on 2nd step cudaerrorinvalidvalue invalid argument`, do you have some advice? thanks~
