### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by qdd1234** [zju3dv/SMAP#19]
您好，可否分享一下数据集的tar包，我这边一直下载不下来，谢谢了

**Comment by raypine** [comment]
Do you only need the annotations ?

**Comment by qdd1234** [comment]
I want  image and annotations ,because in my country , the speed of download is too slow ,the whole time is about 10days
so can you give me a link that i can download image and annotations in china fastly , thank you

**Comment by raypine** [comment]
Sorry, the reason why the official data cannot be downloaded is unknown. So we have no right to spread their data. If the problem cannot be solved, it is recommended to do the experiments on other datasets.
