### ISSUE TITLE
eval code in MuPoTS

### ISSUE THREAD

**Issue by RanFeng** [zju3dv/SMAP#20]
hello, I am also a zju student, and I'm doing my graduate thesis base yours work. but I can't get the result(MPJPE) in yours paper on MuPoTS with your release model. so can you release the eval code in MuPoTS? Thank you so much!!!

**Comment by 4AMZGGO1** [comment]
> hello, I am also a zju student, and I'm doing my graduate thesis base yours work. but I can't get the result(MPJPE) in yours paper on MuPoTS with your release model. so can you release the eval code in MuPoTS? Thank you so much!!!

Have you got the eval code in MuPoTS? I also need that.
