### ISSUE TITLE
eval code in MuPoTS

### ISSUE THREAD

**Issue by 4AMZGGO1** [zju3dv/SMAP#25]
Thank you for sharing your amazing work. I'm doing the research in 3DHPE. I can't get the result(MPJPE) in yours paper on MuPoTS with your release model. so can you release the eval code in MuPoTS?  I'm appreciate it for your help and time.

**Comment by raypine** [comment]
Have you reproject again with the refined depths ?

**Comment by 4AMZGGO1** [comment]
> Have you performed the reprojection again with the refined depths ?
> Nevertheless, we have added the evaluation code to the folder 'lib/eval'. Contact us if you have any question using it.

Thanks a lot for your prompt reply and supplement code.
