### ISSUE TITLE
question abount eval and test code

### ISSUE THREAD

**Issue by 4AMZGGO1** [zju3dv/SMAP#26]
https://github.com/zju3dv/SMAP/blob/9fbcbe4ee2cd6f6d6d6a4e5a05a637629cb5b2e1/lib/eval/convert.py#L31
https://github.com/zju3dv/SMAP/blob/9fbcbe4ee2cd6f6d6d6a4e5a05a637629cb5b2e1/exps/stage3_root2/test.py#L34
I have no idea which json file you used for evaluation. According to my understanding, you may use the test result to eval. In other words, the key of dict "result" in test code should be the same as that of eval code. But it seems that they did not follow the same key as the link I list above.

**Comment by raypine** [comment]
Yeah, the converting code is old and has minor differences with the release code. But it can be easily fixed by replacing 'pred' with 'pred_3d', and 'gt' with 'gt_3d'. Only the rescale and reprojection matter.

**Comment by raypine** [comment]
If you still have problems after fixing these, we will revise the code as soon as possible.

**Comment by 4AMZGGO1** [comment]
> If you still have problems after fixing these, we will revise the code as soon as possible.
THANK YOU VERY MUCH for your instant providing of eval code. I run the code but can not get the metrics MPJPE and RtError. So could you please renew the eval code. I'm appreciate it for your help and time.

**Comment by 4AMZGGO1** [comment]
> If you still have problems after fixing these, we will revise the code as soon as possible.

If you still have problems after fixing these, we will revise the code as soon as possible.
THANK YOU VERY MUCH for your instant providing of eval code. I run the code but can not get the metrics MPJPE and RtError. So could you please renew the eval code. I'm appreciate it for your help and time.
