### ISSUE TITLE
question about testing

### ISSUE THREAD

**Issue by 4AMZGGO1** [zju3dv/SMAP#27]
https://github.com/zju3dv/SMAP/blob/9fbcbe4ee2cd6f6d6d6a4e5a05a637629cb5b2e1/exps/stage3_root2/config.py#L70
Did convert the original format of the moputs dataset to your own format? Could you please release the covert code. I could't find the "M3E_gt.json" in the mopiuts dataset I have downloaded and I can't run the test code, using your model released. Thanks a lot for your time and reading.

**Comment by raypine** [comment]
We have provide the format in 'lib/preprocess'. For MuCo, refer to [https://github.com/zju3dv/SMAP/issues/3#issuecomment-692488374](this issue)

**Comment by 4AMZGGO1** [comment]
I have tried to convert the format of MuPoTS dataset to your formate following what you did for MuCo, but I found that there are still some problem in corverting. Especially, it seems to be several cameras corresponding to the same frame of a image. So which camera did you choose?
And could you please release the coverting code if it's convenient?

**Comment by 4AMZGGO1** [comment]
> We have provide the format in 'lib/preprocess'. For MuCo, refer to [this issue](https://github.com/zju3dv/SMAP/issues/3#issuecomment-692488374), which is similar to the conversion of mupots.

I have tried to convert the format of MuPoTS dataset to your formate following what you did for MuCo, but I found that there are still some problem in corverting. Especially, it seems to be several cameras corresponding to the same frame of a image. So which camera did you choose?
And could you please release the coverting code if it's convenient?
