### ISSUE TITLE
questions about test.sh?

### ISSUE THREAD

**Issue by ch1998** [zju3dv/SMAP#28]
when i run bash test.sh
from cvpack.utils.logger import get_logger
from model.smap import SMAP
from model.refinenet import RefineNet
from lib.utils.dataloader import get_test_loader
from lib.utils.comm import is_main_process
from exps.stage3_root2.test_util import *
from dataset.custom_dataset import CustomDataset

the following error occurred :
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    from cvpack.utils.logger import get_logger
ModuleNotFoundError: No module named 'cvpack'
other modules such as model,lib,exps  can not be found as well.  
how to solve it?

**Comment by 4AMZGGO1** [comment]
It seems that you did not set your HOME_PROJRCT path in train.sh correctly.

**Comment by ch1998** [comment]
> It seems that you did not set your HOME_PROJRCT path in train.sh correctly.

I try to set ：
export PROJECT_HOME='C:\pyproject\SMAP-master'
export PYTHONPATH=$PYTHONPATH:$PROJECT_HOME
python test.py -p "C:\pyproject\SMAP-master\premodels\SMAP_model.pth" \
-t run_inference \
-d test \
-rp "C:\pyproject\SMAP-master\premodels\RefineNet.pth" \
--batch_size 16 \
--do_flip 1 \
--dataset_path "C:\pyproject\SMAP-master\premodelscustom\image_dir"

it has same problem.
I solve the problem by move the test.py,test.sh to C:\pyproject\SMAP-master, and the set is the same as upper.
