### ISSUE TITLE
question about MoCu

### ISSUE THREAD

**Issue by ch1998** [zju3dv/SMAP#29]
the dataset form Moon：
   |-- MuCo
|   |   |-- data
|   |   |   |-- augmented_set
|   |   |   |-- unaugmented_set

for training ，only need the unaugmented_set or all data?

**Comment by ch1998** [comment]
> the dataset form Moon：
> |-- MuCo
> | | |-- data
> | | | |-- augmented_set
> | | | |-- unaugmented_set
> 
> for training ，only need the unaugmented_set or all data?

**Comment by tribeband** [comment]
I cant extract the images after downloading the data. whats wrong wz this?
