### ISSUE TITLE
Error for compilation of association.cpp

### ISSUE THREAD

**Issue by xuchao1688** [zju3dv/SMAP#3]
For pytorch >= 1.1.0, compilation of cpp extension will fail by `expected primary-expression before float` at `hmsIn.data_ptr<float>` in L52 in `association.cpp` with gcc >= 6.0. This is because cpp extension api `tensor.data_ptr` is available in pytorch1.0, however it's moved to `tensor.data` in later version.

**Comment by xuchao1688** [comment]
So for pytorch >= 1.1.0, you can modify `association.cpp` L52 `hmsIn.data_ptr<float>` into `hmsIn.data<float>`. After that, running `python setup.py install` and the compilation will be all okay. I suggest that authors could update pytorch version support according this issue for more people using this repo conveniently.

**Comment by raypine** [comment]
Thanks for your comments. Actually we have tested the installation on several environments: 
1. pytorch 1.4 + gcc 6.5 + cuda 9.2
2. pytorch 1.3/1.4/1.6 + gcc 6/7.5 + cuda 10.1

Our usage `hmsIn.data_ptr<float>` can work on these envs. 
However, with pytorch 1.0/1.1 + cuda 9.0, `hmsIn.data<float>` should be used.
So we are also not sure about it. 
Maybe with pytorch >= 1.3, `hmsIn.data_ptr<float>` is ok, while with pytorch <= 1.1, `hmsIn.data<float>` is ok.
Any suggestions are welcomed.

**Comment by YangJae96** [comment]
@raypine 

How did you train the code?? 
The MuCo, and COCO annotation  format is converted to lib.dataformat.
Do you have the json convert code??

**Comment by raypine** [comment]
@YangJae96 
You can refer to the following code if you want (The 'MuCo-3DHP.json' is from Moon), but it‘s so old that I have not checked it entirely. 
```python
muco2mpi15 = [1, 0, 14, 5, 6, 7, 11, 12, 13, 2, 3, 4, 8, 9, 10]
def format_json(in_path='MuCo-3DHP.json', dataset='MuCo', out_dir=''):
    out_path = osp.join(out_dir, dataset)
    if not osp.exists(out_path):
        os.system("mkdir -p %s"%(out_path))
    with open(in_path, 'r') as f:
        data = json.load(f)

    annotations = data['annotations']
    annot_dict = dict()
    for i, annot in enumerate(annotations):
        img_id = annot['image_id']
        if img_id not in annot_dict.keys():
            annot_dict[img_id] = []
        p2d = np.array(annot['keypoints_img'])[muco2mpi15, :]
        p3d = np.array(annot['keypoints_cam'])[muco2mpi15, :]
        vis = np.array(annot['keypoints_vis'])[muco2mpi15]
        pose = []
        for j in range(15):
            pose_info = [p2d[j, 0], p2d[j, 1], p3d[j, 2]/10, int(vis[j]*2), p3d[j, 0]/10, p3d[j, 1]/10, p3d[j, 2]/10]
            pose.append(pose_info)
        annot_dict[img_id].append(pose)

    output_json = dict()
    output_json['root'] = []
    for img_info in data['images']:
        cur_info = dict()
        cur_info['img_height'] = img_info['height']
        cur_info['img_width'] = img_info['width']
        cur_info['img_paths'] = osp.join('images', img_info['file_name'])
        cur_info['dataset'] = "MuCo"
        cur_info['isValidation'] = 0
        fx, fy = img_info['f']
        cx, cy = img_info['c']
        cur_info['bodys'] = annot_dict[img_info['id']]
        for nh in range(len(cur_info['bodys'])):
            for j in range(len(cur_info['bodys'][nh])):
                cur_info['bodys'][nh][j] += [fx, fy, cx, cy]
        output_json['root'].append(cur_info)
                
    with open(osp.join(out_path, '%s.json'%(dataset)), 'w') as f:
        json.dump(output_json, f)

**Comment by YangJae96** [comment]
@frankie

Thank you so much!!!!!
Have you trained on the MuCO and Coco dataset?
Did you evaluate on the MuPoTS dataset also??



2020년 9월 15일 (화) 오후 3:10, frankie <notifications@github.com>님이 작성:

**Comment by raypine** [comment]
@YangJae96  Moon has provided the evaluation code [here](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/master/data/MuPoTS/mpii_mupots_multiperson_eval.m)

**Comment by YangJae96** [comment]
@frankie 
COCO Keypoints are listed below.
['nose', 'left_eye', 'right_eye', 'left_ear', 'right_ear',
'left_shoulder', 'right_shoulder', 'left_elbow', 'right_elbow', 'left_wrist', 'right_wrist',
left_hip', 'right_hip', 'left_knee', 'right_knee', 'left_ankle', 'right_ankle']

It seems that COCO annotations does not have the "neck, head" keypoints.
How did you make the neck and head keypoints to fit in MPII15 dataset format with coco?

I found the neck can be Inferred as the middle point between the shoulders.
But how is the head keypoint made?

**Comment by raypine** [comment]
Head is not supervised for coco data.
