### ISSUE TITLE
Question about eval code

### ISSUE THREAD

**Issue by 4AMZGGO1** [zju3dv/SMAP#30]
https://github.com/zju3dv/SMAP/blob/9fbcbe4ee2cd6f6d6d6a4e5a05a637629cb5b2e1/lib/eval/mupots_smap.m#L55
I have no idea about the difference about 'annot3' and 'univ_annot3', and why did you use the 'univ_annot3'?  I would so appreciate it if you could give help.

**Comment by raypine** [comment]
Actually we follow Moon and the original code of MuPoTS dataset. The difference between these two type of annotations seems subtle through visualization, which we are also not sure about.
