### ISSUE TITLE
Questions about the meaning of 2D predictions in the final JSON file

### ISSUE THREAD

**Issue by BoYuan96-lab** [zju3dv/SMAP#31]
Hi, thanks for your great work.

I try to run your model on my custom videos. And I notice in the final JSON file, the shape of 2D predictions is (15, 4). I expect the shape is (15, 2) and have no idea why there are 4 values. Could you please clarify the meaning of each coordinate?

**Comment by raypine** [comment]
'4' means : x, y, useless，v (visible if v > 0).
