### ISSUE TITLE
CMU Panoptic dataset config

### ISSUE THREAD

**Issue by lskdje** [zju3dv/SMAP#32]
Thanks for sharing your great work!
I have a question about your experimental details on CMU Panoptic dataset. I see in the code that the V of the "bodys" field is divided into not labeled, locked, and visible. And the confidence of CMUP is between 0 and 1. I'm not sure how to deal with the confidence in the CMUP for SMAP train or test.

**Comment by raypine** [comment]
We transform the label 0, 1 in CMUP to 0, 2 in our format, respectively.

**Comment by lskdje** [comment]
I found that the coordinates of some joints in the CMUP after mapping from the world coordinate system to the image coordinate system will exceed the image boundary of 1902x1080. Could you tell me if these joints in SMAP are involved in training and testing? And the labels of these joints should be set to?

**Comment by raypine** [comment]
No, they are not used and should be set to 0.

**Comment by lskdje** [comment]
Could you also tell me which cameras id to use for training? Thanks very much.

**Comment by raypine** [comment]
Camera 16 and 30. We have stated it in our paper.
