### ISSUE TITLE
CMU dataset test pretrained model

### ISSUE THREAD

**Issue by lskdje** [zju3dv/SMAP#33]
I found that in the paper, the MUCO dataset and CMU dataset were trained separately. So which dataset is the pretraining model downloaded from Google Driver based on? Can I directly test the CMU dataset to reproduce the results in the paper?

**Comment by raypine** [comment]
The provided model is trained on MuCo and CoCo.

**Comment by nicolasugrinovic** [comment]
Hi @raypine, could you please provide the model's weights trained with Panoptic CMU dataset?
Thanks in advance
