### ISSUE TITLE
coordinate conversion 3D to 2D

### ISSUE THREAD

**Issue by funnypig521** [zju3dv/SMAP#35]
Excuse me ,I have some problem in  coordinate conversion.Whether pred_bodys_2d or new_pred_bodys_3d in test.py can not recover the pixel coordinates matching to the origin images.Thanks a lot!(By the way ,your code for 3D HPE works perfect.)

**Comment by raypine** [comment]
The saved results correspond to the resolution of 512x832 (the input size of the network), thus it should be properly padded to match the original images. You can refer to the code [here](https://github.com/zju3dv/SMAP/blob/master/lib/eval/convert.py#L41) for the new pred_2d.

**Comment by raypine** [comment]
consider it has been resolved.
