### ISSUE TITLE
Question about MUCO format

### ISSUE THREAD

**Issue by funnypig521** [zju3dv/SMAP#37]
Excuse me ,I try to train the model and encounter the problem like this:
Traceback (most recent call last):
  File "train.py", line 115, in <module>
    main()
  File "train.py", line 55, in main
    data_loader = get_train_loader(cfg, num_gpu=num_gpu, is_dist=engine.distributed,use_augmentation=True, with_mds=True)
  File "/home/mist/SMAP/lib/utils/dataloader.py", line 23, in get_train_loader
    dataset = Dataset(cfg, 'train', transform, use_augmentation, with_mds)
  File "/home/mist/SMAP/dataset/base_dataset.py", line 43, in __init__
    data = data_this['root'] + data
KeyError: 'root'

As for coco2017, I find create_annot.py to transform the format,and it works.But for MuCo dataset,how to transform its format? My MuCo dateset is downloaded in your link(https://drive.google.com/drive/folders/1yL2ey3aWHJnh8f_nhWP--IyC9krAPsQN).

**Comment by raypine** [comment]
follow this [link](https://github.com/zju3dv/SMAP/issues/3#issuecomment-692488374) to transform the data format.

**Comment by funnypig521** [comment]
Thanks a lot！！！！ @raypine
