### ISSUE TITLE
Error happens when loading pretrained model.

### ISSUE THREAD

**Issue by xuchao1688** [zju3dv/SMAP#4]
_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.

**Comment by raypine** [comment]
Thanks for your comment. We saved the model with pytorch 1.6. So we recommend upgrading pytorch to 1.6 if possible. And we will provide the model saved by a older version of pytorch as soon as possible.

**Comment by raypine** [comment]
We have update the model.
