### ISSUE TITLE
Question abount your Depth-Aware Part Association

### ISSUE THREAD

**Issue by xunhui-huang** [zju3dv/SMAP#40]
Firstly,Thanks for your code sharing!But I have some confusion about your referred Depth-Aware Part Association.I don't find this part in your code.especislly**,you mentioned that you sort joints from near to far according to the predicted root depth,and your association process starts with the root and proceeds along the skeleton tree successively.**I don't understand your detailed algorithm process.Would you please provide more detailed explanation about this part and give a hit on your relative code position?

**Comment by raypine** [comment]
The part is [here](https://github.com/zju3dv/SMAP/blob/master/extensions/association.cpp#L144).
