### ISSUE TITLE
question about Panoptic

### ISSUE THREAD

**Issue by HuiliCui** [zju3dv/SMAP#43]
Thanks for your sharing. There are some questions about Panoptic.
1. Which sequence of  Panoptic data has been used during training
2. Can you share 160422_mifia2's 3D pose annotation, because the official website is now unavailable

Thank you in advance

**Comment by raypine** [comment]
1. It can be found in #1 
2. It may involve the license problem if the website doesn't provide it, thus it is suggested to ask the authors of CMU Panoptic.
