### ISSUE TITLE
evaluation about MuPoTs-3d

### ISSUE THREAD

**Issue by HuiliCui** [zju3dv/SMAP#49]
Hi， I want to test the results on the MUPOTS dataset. The script settings are as follows
![image](https://user-images.githubusercontent.com/62087070/159432506-b89fba0e-1bb7-4d32-af2b-c26a4d4600e4.png)
and in convert.py I use the K from  MuPoTs-3D
then set eval_mode = 1;is_relative = 0; in mupots-smap.m, The result is very poor! Could you tell me what went wrong?
![image](https://user-images.githubusercontent.com/62087070/159433292-5dc3c37f-2da1-4dc6-a36f-981ccde12441.png)

**Comment by raypine** [comment]
test_mode: generate_result
do_flip: 1
Then use the code in lib/eval.

**Comment by HuiliCui** [comment]
![image](https://user-images.githubusercontent.com/62087070/159617257-50ca3950-255b-4a08-b681-24b4471eba88.png)
Thank you very much for your reply！Could you provide this file M3E_gt.json？

**Comment by raypine** [comment]
I upload the file via this [link](https://drive.google.com/file/d/1-E-omxD89tJUm5wYCPR0_3JzetSYfxkW/view?usp=sharing).
But I have not checked it totally. You can have a try if possible.

**Comment by HuiliCui** [comment]
It helps a lot! I have obtained the right results! Could you tell me what should I do about testing the Panoptic dataset?

**Comment by raypine** [comment]
The model we provided is only for MuPoTS-3D. Unfortunately, it's difficult to find the model trained on the Panoptic dataset now.
But according to our experience, to achieve the performance in our paper (even better) is easy, since the distribution of training data is close to that of testing data to some extent, e.g. the camera viewing angle, the environment.
If you want to perform the experiments on the Panoptic dataset, you could finetune our provided model or train from scratch on it.

**Comment by HuiliCui** [comment]
That means the provided model is not trained by panoptic dataset?

**Comment by raypine** [comment]
Yes, it's trained with MuCo and tested on MuPoTS-3D.

**Comment by jihao0309** [comment]
Hello，i followed the test script above, and the visualization of the results is good, both 2d and 3d. Then i want to transform the format of result from json to matlab, i commented the code that i think it is unnecessary in convert.py.
![image](https://user-images.githubusercontent.com/62428858/162903292-2466eb84-3de1-40da-bb23-b7c15c64a141.png)

The results pose2d.mat and pose3d.mat in matlab format were obtained. Next, i run the code mupots_smal.m, set eval_mode=1 and is_relative=1, i guess in this way, i can get the PCK_abs. But the results are worse than the results in paper.The average PCK_abs is about 68. Is there anything wrong with what I'm doing, please point it out, thanks a lot！！！
![image](https://user-images.githubusercontent.com/62428858/162903326-a986aaeb-b055-411d-9df7-535174796afc.png)

**Comment by raypine** [comment]
Why do you comment them ? Since we resize the input image to the resolution of 512 x 832, it's necessary to transform the estimation to the actual scale.

**Comment by jihao0309** [comment]
Sorry, I made a mistake in another place, I can reproduce the result now, thanks!

**Comment by jihao0309** [comment]
> Why do you comment them ? Since we resize the input image to the resolution of 512 x 832, it's necessary to transform the estimation to the actual scale.

Sorry, I made a mistake in another place, I can get the right result now, thanks!
