### ISSUE TITLE
Can't install dapalib

### ISSUE THREAD

**Issue by HarrytheOrange** [zju3dv/SMAP#58]
Traceback (most recent call last):
  File "run.py", line 17, in <module>
    import dapalib
ModuleNotFoundError: No module named 'dapalib'

▶ pip install dapalib
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement dapalib (from versions: none)
ERROR: No matching distribution found for dapalib

**Comment by HarrytheOrange** [comment]
Hi, the problem occurs when I tied to install dapalib, which can not be located anywhere on internet. Do you know how to figure out this problem?

**Comment by raypine** [comment]
Read the **Start** section in README
