### ISSUE TITLE
the camera internal parameters of the MuPoTS-3D dataset ?

### ISSUE THREAD

**Issue by ZXin0305** [zju3dv/SMAP#59]
Hello, I want to test the result on the MuPoTS-3D dataset, but I cannot find the camera internal parameters [fx, fy, cx, cy] of the dataset ..Could you tell me how to get it ?? Thanks a lot !!!

**Comment by raypine** [comment]
I am not sure the original data structure, but the [data ](https://drive.google.com/file/d/1wZ_QdqDzYqz1Lh4Yqf_-dSC568CFnfA0/view)from Moon provides what you need.
