### ISSUE TITLE
Refinet/test.py issue

### ISSUE THREAD

**Issue by YangJae96** [zju3dv/SMAP#9]
After I ran commad below.
![캡처2](https://user-images.githubusercontent.com/57695621/93707180-4d947680-fb67-11ea-8208-25f9796b05bb.PNG)

set -t generate_result
set -d test 
exps/stage3_root2/bash test.sh
Then, I have obtained the json file  "stage3_root2_generate_result_test_.json".

After getting the json files I tried to run refinet/test.py scripy by using bash exps/refinet/test.sh.
But the code did not run so I changed it to make it run and got the results below.
![캡처](https://user-images.githubusercontent.com/57695621/93707148-26d64000-fb67-11ea-9d5b-116df44901fa.PNG)

The result is root error of mean 49%. But in p2p_dataset.py the code seems to be making 
the distance between 3d joints and relative to the root joint. 

Is exps/refinet/test.py caculating  PCKroot? or PCKrel.
Could you please give some more detailed explanation about the code in the readme??

Thanks

**Comment by raypine** [comment]
If you want to prepare the training data for RefineNet:
```
set -t generate_train
set -d generation
```
The exps/refinenet/test.py is just used to pick the best model. It calculates MPJPE.

**Comment by YangJae96** [comment]
Thank you for your quick reply!

I have one more question.
The result from exps/stage3_root2/test.py which  are 

3d_pairs has items like{'pred_2d':[[x,y,detZ,score]...], 'gt_2d':[[x,y,Z,visual_type]...],
                            'pred_3d':[[X,Y,Z,score]...], 'gt_3d':[[X,Y,Z]...],
                            'root_d': (abs depth of root (float value) pred by network),
                             'image_path': relative image path}

It doesn't match the joint num with the evaluation code that you used.
The below is Moons code that you provided.
https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/master/data/MuPoTS/mpii_mupots_multiperson_eval.m

I think the eval matlab moons code converts the joints into MPII15 format? 
Even thought, your SMAP code already has MPII15 joints but I keep getting error.

![evalerror](https://user-images.githubusercontent.com/57695621/93715667-9f5bf180-fba5-11ea-8ed2-9eecc122559b.PNG)

Am I missing something?
What more setting should I do to make pred_2d and pred_3d to make result using matlab code??

**Comment by raypine** [comment]
Several things need to do before evaluating on the MuPoTS-3D dataset:
- If using RefineNet, the refined depths of every joint except root are used to recalculate their new X, Y by reprojection. (optional)
- Mapping the skeleton (mpi15 --> mupots (or moon) )
- modify some codes relevant to skeleton.

**Comment by raypine** [comment]
Several things need to do before evaluating on the MuPoTS-3D dataset:
- Mapping the skeleton (mpi15 --> mupots (or moon) )
- modify some codes relevant to skeleton.

**Comment by YangJae96** [comment]
@raypine 

Do you mean modifying code relevant to skeleton? => Change matlab code?

Also, the pred_2d does not match with the original GT image because the network 
output is fit into 832x512 but the GT image is 1920x1080.  
![캡처](https://user-images.githubusercontent.com/57695621/93739136-87768300-fc22-11ea-83da-865c14a2f105.PNG)

Do I need to change the value of pred_2d and pred_3d by 
 in order to match the GT when using matlab eval code?

**Comment by raypine** [comment]
A1: Yes, something like `o1, num_joints, safe_traversal_order' in MATALB code.
A2: You only need to change pred_2d to match the original image size. Pred_3d needs no change. Note that the recovery should be the reverse process of that in dataloader.

**Comment by YangJae96** [comment]
What do you mean by  "Pred_3d needs no change except for the unit (check it)"??
